name: AdminTools
version: 1.0
main: de.cric_hammel.admintools.Main
api-version: 1.20

commands:
   getitems:
      description: Open the menu with all the AdminTools
   admintools:
      description: Display command overview